baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Wattanit Hotrakool"
theme = "hermit"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Personal Website"
  footerCopyright = 'Wattanit Hotrakool &#183; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/"

  [[params.social]]
    name = "github"
    url = "https://github.com/"

[menu]

  [[menu.main]]
    name = "Research"
    url = "research/"
    weight = 10

  [[menu.main]]
    name = "Business"
    url = "business/"
    weight = 20

  [[menu.main]]
    name = "Blogs"
    url = "posts/"
    weight = 30

  [[menu.main]]
    name = "Hobbies"
    url = "hobbies/"
    weight = 40
